name: Labeler

on: [pull_request]

jobs:
  autolabel:
    runs-on: ubuntu-latest
    name: Label the pull request
    steps:
      - name: Pull request size labeler
        uses: xavitechec/gh-action-pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
